### ISSUE TITLE
FOG Local does not handle Tempfiles correct

### ISSUE THREAD

**Issue by Jeremy-Walton** [fog/fog-local#6]
https://github.com/fog/fog-local/blob/master/lib/fog/storage/local/models/file.rb#L104

If a Tempfile is sent, it will end up in the last else statement and read out the entire file. For large uploads(hundreds of MB and up), this greatly increases the processing time for uploading a file.

Also, you should consider using FileUtils.mv which only works for Tempfile rather than FileUtils.cp. It is quite a bit faster (10ish second difference in our case)

Here is an example of my use case

Old slow code

```
fog_directory().files.create(
  key:  pathname + uuid,
  body: file,
  encryption: 'AES256'
)
```

This is what we had to do instead

```
path = root_directory.join(pathname)
FileUtils.mkdir_p path
FileUtils.cp file.path, path.join(uuid)
```

Processing time went from an average of 40 seconds to 20 seconds

If we then change the FileUtils.cp to FileUtils.mv, the average time went down to 12 seconds.

```
FileUtils.mv file.path, path.join(uuid)
```

**Comment by timirwin** [comment]
Great information

**Comment by lautis** [comment]
Nice catch with tempfiles! That is definitely something that should be addressed.

Using mv instead of cp sounds a bit risky. As a side-effect the uploaded file wouldn't exist in the original location, which is not quite what I'd expect especially as other adapters won't change the original file. 

There could be a configuration option, but I'd lean on keeping local as similar as possible to the remote counterparts. If you're keen on having the best possible performance, I'd recommend using raw file operations.
